import React, { useEffect, useRef, useState } from "react";
import { QRCodeCanvas } from "qrcode.react";
import { Html5Qrcode } from "html5-qrcode";
import { useNavigate } from "react-router-dom";
import Layout from "../components/Layout.jsx";
import { api, getSession } from "../api.js";
import Notice from "../components/Notice.jsx";

export default function Pay(){const session=getSession();const nav=useNavigate();const [wallet,setWallet]=useState(null);const [mode,setMode]=useState("create");const [form,setForm]=useState({address:"",amount:"",category:"CANTEEN",note:""});const[message,setMessage]=useState("");const scanner=useRef(null);useEffect(()=>{api.wallet(session.userId).then(setWallet).catch(e=>setMessage(e.message));return()=>{if(scanner.current){scanner.current.stop().catch(()=>{});scanner.current.clear();scanner.current=null}}},[]);const set=k=>e=>setForm({...form,[k]:e.target.value});const payload=JSON.stringify({address:form.address,amount:Number(form.amount||0),category:form.category,note:form.note});
async function startScan(){setMessage("");if(scanner.current)return;const qr=new Html5Qrcode("qr-reader");scanner.current=qr;try{await qr.start({facingMode:"environment"},{fps:10,qrbox:{width:250,height:250}},text=>{try{const d=JSON.parse(text);setForm({address:d.address||"",amount:d.amount||"",category:d.category||"OTHER",note:d.note||""});setMessage("QR scanned. Verify the payment details before sending.");setMode("scan");qr.stop().then(()=>{qr.clear();scanner.current=null}).catch(()=>{});}catch{setMessage("This QR code is not a valid wallet payment QR.")}},()=>{});}catch(e){setMessage("Camera could not start. Allow camera permission or use the Create QR tab.");scanner.current=null;}}
return <Layout title="QR Pay" subtitle="Create a payment QR or scan one from a campus wallet."><Notice message={message} type={message.includes("scanned")?"success":"error"}/><div className="tabs"><button className={mode==="create"?"tab active":"tab"} onClick={()=>setMode("create")}>Create QR</button><button className={mode!=="create"?"tab active":"tab"} onClick={()=>setMode("scan")}>Scan QR</button></div>{mode==="create"?<div className="qr-pay-grid"><section className="panel"><h2>Payment QR</h2><p className="muted">Enter the campus payment details and let the receiver scan it.</p><div className="form-grid"><label>Receiver wallet<input value={form.address} onChange={set("address")} placeholder="WALLET-2"/></label><label>Amount<input type="number" value={form.amount} onChange={set("amount")} placeholder="50"/></label><label>Category<select value={form.category} onChange={set("category")}><option>CANTEEN</option><option>TRANSPORT</option><option>COLLEGE STORE</option><option>PRINTING</option><option>EDUCATION</option><option>EVENTS</option><option>OTHER</option></select></label><label>Note<input value={form.note} onChange={set("note")} placeholder="Lunch"/></label></div></section><section className="panel center"><QRCodeCanvas value={payload} size={250} includeMargin/><p className="qr-caption">Scan with this project's QR Pay page.</p></section></div>:<div className="scan-layout"><section className="panel center"><div id="qr-reader" className="scanner"></div><button className="primary-btn" onClick={startScan}>Start camera</button></section><section className="panel"><h2>Scanned payment</h2><div className="scan-details"><span>Receiver<strong>{form.address||"—"}</strong></span><span>Amount<strong>{form.amount||"—"}</strong></span><span>Category<strong>{form.category}</strong></span><span>Note<strong>{form.note||"—"}</strong></span></div><button className="primary-btn" disabled={!form.address||!form.amount} onClick={()=>nav("/send",{state:form})}>Continue to payment →</button></section></div>}</Layout>}
