import React, { useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import Layout from "../components/Layout.jsx";
import Notice from "../components/Notice.jsx";
import { api, getSession } from "../api.js";

const cats=["CANTEEN","TRANSPORT","COLLEGE STORE","PRINTING","EDUCATION","EVENTS","OTHER"];
export default function Send(){const session=getSession();const loc=useLocation();const navigate=useNavigate();const [form,setForm]=useState({address:loc.state?.address||"",amount:loc.state?.amount||"",category:loc.state?.category||"OTHER",note:loc.state?.note||""});const [recipient,setRecipient]=useState(null);const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const set=k=>e=>setForm({...form,[k]:e.target.value});
async function find(){setMessage("");try{const r=await api.recipient(form.address.trim());if(!r.found)throw new Error(r.message||"Wallet not found");setRecipient(r)}catch(e){setRecipient(null);setMessage(e.message)}}
async function submit(e){e.preventDefault();setBusy(true);setMessage("");try{await api.send(session.userId,form);navigate("/wallet");}catch(e){setMessage(e.message)}finally{setBusy(false)}}
return <Layout title="Send payment" subtitle="Transfer funds to a student or campus wallet."><div className="content-grid"><section className="panel"><h2>Payment details</h2><Notice message={message} type="error"/><form className="form-stack" onSubmit={submit}><label>Receiver wallet address<div className="inline-field"><input value={form.address} onChange={set("address")} placeholder="WALLET-2" required/><button type="button" className="secondary-btn" onClick={find}>Find</button></div></label>{recipient&&<div className="recipient"><div className="avatar">{recipient.name?.slice(0,1)}</div><div><b>{recipient.name}</b><span>{recipient.studentId||"Student"} · {recipient.department||""}</span><small>{recipient.address}</small></div></div>}<label>Amount<input type="number" min="0.01" step="0.01" value={form.amount} onChange={set("amount")} required/></label><label>Campus category<select value={form.category} onChange={set("category")}>{cats.map(c=><option key={c}>{c}</option>)}</select></label><label>Payment note<input maxLength="100" value={form.note} onChange={set("note")} placeholder="Lunch, printing, bus pass..."/></label><button className="primary-btn" disabled={busy}>{busy?"Sending...":"Confirm payment"}</button></form></section><aside className="panel soft"><h3>Student payment</h3><p>Use this page for student-to-student transfers and campus payments. Always verify the receiver before confirming.</p><div className="tip-list"><span>✓ Receiver lookup</span><span>✓ Category tracking</span><span>✓ Payment notes</span><span>✓ Transaction history</span></div></aside></div></Layout>}
